require 'mustache'
require 'active_support/core_ext/string'

require "fierce/version"
require 'fierce/handler'
require 'fierce/stage_manager'
require 'fierce/master_of_ceremonies'
require 'fierce/view_model'
require 'fierce/delegate_generator/controller'
require 'fierce/config'
require 'fierce/presenter_finder'
require 'fierce/railtie'
require 'fierce/renderer'
require 'fierce/partial_finder'
require 'fierce/presenter'
